//! 阅读会话、历史汇总与日历统计。

use std::collections::BTreeMap;

use serde::{Deserialize, Serialize};
use serde_json::{Value, json};

use crate::{
    models::CURRENT_SCHEMA_VERSION,
    resources::{ResourceRef, ResourceStore},
};

use super::common::{current_schema_version, ensure_document, validate_id};

const HISTORY_PATH: &str = "resource://reading-history.json";

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct ReadingHistoryDocument {
    #[serde(default = "current_schema_version")]
    pub schema_version: u32,
    #[serde(default)]
    pub sessions: Vec<ReadingSession>,
    #[serde(default)]
    pub books: Vec<BookReadingSummary>,
    /// Local-calendar buckets for heatmaps and today/week/month summaries.
    #[serde(default)]
    pub days: Vec<DailyReadingSummary>,
    #[serde(default)]
    pub total_duration_ms: u64,
    #[serde(default)]
    pub total_sessions: u64,
}

impl Default for ReadingHistoryDocument {
    fn default() -> Self {
        Self {
            schema_version: CURRENT_SCHEMA_VERSION,
            sessions: Vec::new(),
            books: Vec::new(),
            days: Vec::new(),
            total_duration_ms: 0,
            total_sessions: 0,
        }
    }
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct ReadingSession {
    pub book_id: String,
    /// Stable identifier generated by the UI for one completed reading visit.
    /// Retrying persistence with the same identifier never counts the visit twice.
    pub session_id: String,
    pub duration_ms: u64,
    pub ended_at_ms: u64,
    /// Minutes east of UTC, sampled by the UI when the session ends.
    #[serde(default)]
    pub utc_offset_minutes: i32,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct BookReadingSummary {
    pub book_id: String,
    pub session_count: u64,
    pub total_duration_ms: u64,
    pub last_read_at_ms: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct DailyReadingSummary {
    /// Local date as `YYYYMMDD`, suitable for a reading heatmap.
    pub day: String,
    pub session_count: u64,
    pub total_duration_ms: u64,
    pub books: Vec<BookDailySummary>,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct BookDailySummary {
    pub book_id: String,
    pub session_count: u64,
    pub total_duration_ms: u64,
}

pub async fn reading_history_resource(store: &ResourceStore) -> Result<ResourceRef, String> {
    ensure_document(store, history_ref(), ReadingHistoryDocument::default()).await
}

/// Build processed reading summaries for one UTC millisecond window without
/// changing the persisted history or returning its raw sessions.
pub async fn reading_statistics(
    store: &ResourceStore,
    from_ms: u64,
    to_ms: u64,
) -> Result<Value, String> {
    const MAX_WINDOW_MS: u64 = 31 * 24 * 60 * 60 * 1_000;
    if from_ms >= to_ms {
        return Err("Reading statistics range must satisfy fromMs < toMs".to_owned());
    }
    if to_ms - from_ms > MAX_WINDOW_MS {
        return Err("Reading statistics range must not exceed 31 days".to_owned());
    }

    let history = store
        .read_json_ref(&history_ref())
        .await
        .map_err(|error| error.to_string())?;
    let mut document = history_document(&history)?;
    let mut sessions = Vec::with_capacity(document.sessions.len());
    for mut session in document.sessions {
        if session.duration_ms == 0
            || session.duration_ms > session.ended_at_ms
            || !(-840..=840).contains(&session.utc_offset_minutes)
        {
            return Err("Reading history contains invalid session data".to_owned());
        }
        let session_start = session.ended_at_ms - session.duration_ms;
        let clipped_start = from_ms.max(session_start);
        let clipped_end = to_ms.min(session.ended_at_ms);
        if clipped_start < clipped_end {
            session.duration_ms = clipped_end - clipped_start;
            session.ended_at_ms = clipped_end;
            sessions.push(session);
        }
    }
    document.sessions = sessions;
    rebuild_reading_summaries(&mut document);

    Ok(json!({
        "books": document.books,
        "days": document.days,
        "totalDurationMs": document.total_duration_ms,
        "totalSessions": document.total_sessions,
    }))
}

/// Persist one completed reading visit and recompute its per-book aggregates.
/// Replaying a save with the same `sessionId` replaces that session record
/// instead of adding its duration again.
pub async fn record_reading_session(
    store: &ResourceStore,
    session: ReadingSession,
) -> Result<ResourceRef, String> {
    validate_id(&session.book_id, "bookId")?;
    validate_id(&session.session_id, "sessionId")?;
    if session.ended_at_ms == 0 {
        return Err("Reading session endedAtMs must be positive".to_owned());
    }
    if session.duration_ms == 0 || session.duration_ms > session.ended_at_ms {
        return Err(
            "Reading session duration must be positive and no longer than its timestamp".to_owned(),
        );
    }
    if !(-840..=840).contains(&session.utc_offset_minutes) {
        return Err("Reading session UTC offset must be within -14:00 to +14:00".to_owned());
    }
    let document = store
        .update_json_ref(&history_ref(), move |mut value| {
            let mut document = history_document(&mut value)?;
            if let Some(existing) = document
                .sessions
                .iter_mut()
                .find(|existing| existing.session_id == session.session_id)
            {
                if existing.book_id != session.book_id {
                    return Err("Reading session ID already belongs to another book".to_owned());
                }
                *existing = session;
            } else {
                document.sessions.push(session);
            }
            document.schema_version = CURRENT_SCHEMA_VERSION;
            rebuild_reading_summaries(&mut document);
            serde_json::to_value(document).map_err(|error| error.to_string())
        })
        .await
        .map_err(|error| error.to_string())?;
    let _ = document;
    Ok(history_ref())
}

pub async fn delete_reading_history_for_book(
    store: &ResourceStore,
    book_id: &str,
) -> Result<ResourceRef, String> {
    validate_id(book_id, "bookId")?;
    store
        .update_json_ref(&history_ref(), move |value| {
            let mut document = history_document(&value)?;
            document
                .sessions
                .retain(|session| session.book_id != book_id);
            rebuild_reading_summaries(&mut document);
            serde_json::to_value(document).map_err(|error| error.to_string())
        })
        .await
        .map_err(|error| error.to_string())?;
    Ok(history_ref())
}

pub async fn clear_reading_history(store: &ResourceStore) -> Result<ResourceRef, String> {
    store
        .update_json_ref(&history_ref(), |_| {
            serde_json::to_value(ReadingHistoryDocument::default())
                .map_err(|error| error.to_string())
        })
        .await
        .map_err(|error| error.to_string())?;
    Ok(history_ref())
}

fn history_document(value: &Value) -> Result<ReadingHistoryDocument, String> {
    if value.is_null() {
        return Ok(ReadingHistoryDocument::default());
    }
    serde_json::from_value(value.clone())
        .map_err(|error| format!("Invalid reading history JSON: {error}"))
}

fn rebuild_reading_summaries(document: &mut ReadingHistoryDocument) {
    let mut summaries = BTreeMap::<String, BookReadingSummary>::new();
    let mut daily = BTreeMap::<String, MutableDailySummary>::new();
    let mut total_duration_ms = 0u64;
    for session in &document.sessions {
        total_duration_ms = total_duration_ms.saturating_add(session.duration_ms);
        let summary =
            summaries
                .entry(session.book_id.clone())
                .or_insert_with(|| BookReadingSummary {
                    book_id: session.book_id.clone(),
                    session_count: 0,
                    total_duration_ms: 0,
                    last_read_at_ms: 0,
                });
        summary.session_count = summary.session_count.saturating_add(1);
        summary.total_duration_ms = summary
            .total_duration_ms
            .saturating_add(session.duration_ms);
        summary.last_read_at_ms = summary.last_read_at_ms.max(session.ended_at_ms);

        for (day, duration) in split_session_by_local_day(session) {
            let entry = daily.entry(day).or_default();
            entry.session_count = entry.session_count.saturating_add(1);
            entry.total_duration_ms = entry.total_duration_ms.saturating_add(duration);
            let book = entry
                .books
                .entry(session.book_id.clone())
                .or_insert_with(|| MutableBookDailySummary {
                    book_id: session.book_id.clone(),
                    session_count: 0,
                    total_duration_ms: 0,
                });
            book.session_count = book.session_count.saturating_add(1);
            book.total_duration_ms = book.total_duration_ms.saturating_add(duration);
        }
    }
    document.books = summaries.into_values().collect();
    document
        .books
        .sort_by(|left, right| right.last_read_at_ms.cmp(&left.last_read_at_ms));
    document.total_duration_ms = total_duration_ms;
    document.total_sessions = document.sessions.len() as u64;
    document.days = daily
        .into_iter()
        .rev()
        .map(|(day, value)| DailyReadingSummary {
            day,
            session_count: value.session_count,
            total_duration_ms: value.total_duration_ms,
            books: value
                .books
                .into_values()
                .map(|book| BookDailySummary {
                    book_id: book.book_id,
                    session_count: book.session_count,
                    total_duration_ms: book.total_duration_ms,
                })
                .collect(),
        })
        .collect();
}

#[derive(Default)]
struct MutableDailySummary {
    session_count: u64,
    total_duration_ms: u64,
    books: BTreeMap<String, MutableBookDailySummary>,
}

struct MutableBookDailySummary {
    book_id: String,
    session_count: u64,
    total_duration_ms: u64,
}

fn split_session_by_local_day(session: &ReadingSession) -> Vec<(String, u64)> {
    const DAY_MS: i128 = 86_400_000;
    const MINUTE_MS: i128 = 60_000;
    let end = session.ended_at_ms as i128;
    let mut cursor = end - session.duration_ms as i128;
    let offset = session.utc_offset_minutes as i128 * MINUTE_MS;
    let mut pieces = Vec::new();
    while cursor < end {
        let day_number = (cursor + offset).div_euclid(DAY_MS);
        let next_utc_day = (day_number + 1) * DAY_MS - offset;
        let segment_end = end.min(next_utc_day);
        if segment_end <= cursor {
            break;
        }
        pieces.push((civil_day_key(day_number), (segment_end - cursor) as u64));
        cursor = segment_end;
    }
    pieces
}

/// Convert days since 1970-01-01 to a proleptic Gregorian `YYYYMMDD` key.
fn civil_day_key(days_since_epoch: i128) -> String {
    let z = days_since_epoch as i64 + 719_468;
    let era = (if z >= 0 { z } else { z - 146_096 }).div_euclid(146_097);
    let day_of_era = z - era * 146_097;
    let year_of_era =
        (day_of_era - day_of_era / 1_460 + day_of_era / 36_524 - day_of_era / 146_096) / 365;
    let mut year = year_of_era + era * 400;
    let day_of_year = day_of_era - (365 * year_of_era + year_of_era / 4 - year_of_era / 100);
    let month_prime = (5 * day_of_year + 2) / 153;
    let day = day_of_year - (153 * month_prime + 2) / 5 + 1;
    let month = month_prime + if month_prime < 10 { 3 } else { -9 };
    year += (month <= 2) as i64;
    format!("{year:04}{month:02}{day:02}")
}

fn history_ref() -> ResourceRef {
    ResourceRef::new(HISTORY_PATH).expect("static reading history reference is valid")
}
