//! JSON-backed reading adjuncts: bookmarks, history, display replacements,
//! and shelf organization. This module never evaluates display replacements;
//! JavaScript applies them to the already processed chapter while rendering.

use std::{
    collections::BTreeMap,
    time::{SystemTime, UNIX_EPOCH},
};

use serde::{Deserialize, Serialize};
use serde_json::{json, Value};

use crate::{
    models::CURRENT_SCHEMA_VERSION,
    resources::{ResourceRef, ResourceStore},
};

const BOOKMARKS_PATH: &str = "resource://bookmarks.json";
const HISTORY_PATH: &str = "resource://reading-history.json";
const REPLACEMENTS_PATH: &str = "resource://replacement-rules.json";

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct BookmarkDocument {
    #[serde(default = "current_schema_version")]
    pub schema_version: u32,
    #[serde(default)]
    pub bookmarks: Vec<Bookmark>,
}

impl Default for BookmarkDocument {
    fn default() -> Self {
        Self {
            schema_version: CURRENT_SCHEMA_VERSION,
            bookmarks: Vec::new(),
        }
    }
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct Bookmark {
    pub id: String,
    pub book_id: String,
    pub chapter_index: usize,
    pub offset: u64,
    #[serde(default)]
    pub note: String,
    pub created_at_ms: u64,
    pub updated_at_ms: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BookmarkInput {
    #[serde(default)]
    pub id: Option<String>,
    pub book_id: String,
    pub chapter_index: usize,
    pub offset: u64,
    #[serde(default)]
    pub note: String,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct ReadingHistoryDocument {
    #[serde(default = "current_schema_version")]
    pub schema_version: u32,
    #[serde(default)]
    pub sessions: Vec<ReadingSession>,
    #[serde(default)]
    pub books: Vec<BookReadingSummary>,
    /// Local-calendar buckets for heatmaps and today/week/month summaries.
    #[serde(default)]
    pub days: Vec<DailyReadingSummary>,
    #[serde(default)]
    pub total_duration_ms: u64,
    #[serde(default)]
    pub total_sessions: u64,
}

impl Default for ReadingHistoryDocument {
    fn default() -> Self {
        Self {
            schema_version: CURRENT_SCHEMA_VERSION,
            sessions: Vec::new(),
            books: Vec::new(),
            days: Vec::new(),
            total_duration_ms: 0,
            total_sessions: 0,
        }
    }
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct ReadingSession {
    pub book_id: String,
    /// Stable identifier generated by the UI for one completed reading visit.
    /// Retrying persistence with the same identifier never counts the visit twice.
    pub session_id: String,
    pub duration_ms: u64,
    pub ended_at_ms: u64,
    /// Minutes east of UTC, sampled by the UI when the session ends.
    #[serde(default)]
    pub utc_offset_minutes: i32,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct BookReadingSummary {
    pub book_id: String,
    pub session_count: u64,
    pub total_duration_ms: u64,
    pub last_read_at_ms: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct DailyReadingSummary {
    /// Local date as `YYYYMMDD`, suitable for a reading heatmap.
    pub day: String,
    pub session_count: u64,
    pub total_duration_ms: u64,
    pub books: Vec<BookDailySummary>,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct BookDailySummary {
    pub book_id: String,
    pub session_count: u64,
    pub total_duration_ms: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct ReplacementRuleDocument {
    #[serde(default = "current_schema_version")]
    pub schema_version: u32,
    #[serde(default)]
    pub rules: Vec<DisplayReplacementRule>,
}

impl Default for ReplacementRuleDocument {
    fn default() -> Self {
        Self {
            schema_version: CURRENT_SCHEMA_VERSION,
            rules: Vec::new(),
        }
    }
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct DisplayReplacementRule {
    pub id: String,
    pub name: String,
    pub pattern: String,
    pub replacement: String,
    pub enabled: bool,
    pub is_regex: bool,
    /// `all` or `book:<book-id>`; interpretation and replacement happen in JS.
    pub scope: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct DisplayReplacementRuleInput {
    #[serde(default)]
    pub id: Option<String>,
    pub name: String,
    pub pattern: String,
    #[serde(default)]
    pub replacement: String,
    pub enabled: bool,
    pub is_regex: bool,
    #[serde(default = "default_replacement_scope")]
    pub scope: String,
}

#[derive(Clone, Copy, Debug, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub enum ShelfSortKey {
    UpdatedAt,
    Title,
    Author,
    LatestChapter,
    Progress,
    Custom,
}

#[derive(Clone, Copy, Debug, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub enum ShelfSortOrder {
    Ascending,
    Descending,
}

/// Initialize a missing bookmark document and return its stable public resource
/// reference. The caller can turn it into the current runtime URL for the UI.
pub async fn bookmarks_resource(store: &ResourceStore) -> Result<ResourceRef, String> {
    ensure_document(store, bookmarks_ref(), BookmarkDocument::default()).await
}

/// Create or update a bookmark. Existing IDs retain their creation timestamp
/// and cannot be reassigned to a different book.
pub async fn upsert_bookmark(
    store: &ResourceStore,
    input: BookmarkInput,
) -> Result<ResourceRef, String> {
    validate_id(&input.book_id, "bookId")?;
    if input.note.len() > 16_384 {
        return Err("Bookmark note exceeds 16 KiB".to_owned());
    }

    let id = match input.id {
        Some(id) => {
            validate_id(&id, "bookmarkId")?;
            id
        }
        None => format!("bookmark-{}", uuid::Uuid::new_v4().simple()),
    };
    let updated_at_ms = now_ms();
    let mut created_at_ms = updated_at_ms;
    let document = store
        .update_json_ref(&bookmarks_ref(), move |mut value| {
            let mut document = bookmark_document(&mut value)?;
            let existing = document
                .get_mut("bookmarks")
                .and_then(Value::as_array_mut)
                .expect("default bookmark document has an array");
            if let Some(position) = existing.iter().position(|bookmark| {
                bookmark.get("id").and_then(Value::as_str) == Some(id.as_str())
            }) {
                let old = &existing[position];
                if old.get("bookId").and_then(Value::as_str) != Some(&input.book_id) {
                    return Err("Bookmark ID already belongs to another book".to_owned());
                }
                created_at_ms = old
                    .get("createdAtMs")
                    .and_then(Value::as_u64)
                    .unwrap_or(updated_at_ms);
                existing[position] = json!({
                    "id": id,
                    "bookId": input.book_id,
                    "chapterIndex": input.chapter_index,
                    "offset": input.offset,
                    "note": input.note,
                    "createdAtMs": created_at_ms,
                    "updatedAtMs": updated_at_ms,
                });
            } else {
                existing.push(json!({
                    "id": id,
                    "bookId": input.book_id,
                    "chapterIndex": input.chapter_index,
                    "offset": input.offset,
                    "note": input.note,
                    "createdAtMs": created_at_ms,
                    "updatedAtMs": updated_at_ms,
                }));
            }
            document["schemaVersion"] = json!(CURRENT_SCHEMA_VERSION);
            Ok(document)
        })
        .await
        .map_err(|error| error.to_string())?;
    let _ = document;
    Ok(bookmarks_ref())
}

pub async fn delete_bookmark(store: &ResourceStore, id: &str) -> Result<ResourceRef, String> {
    validate_id(id, "bookmarkId")?;
    store
        .update_json_ref(&bookmarks_ref(), |mut value| {
            let mut document = bookmark_document(&mut value)?;
            let bookmarks = document
                .get_mut("bookmarks")
                .and_then(Value::as_array_mut)
                .expect("default bookmark document has an array");
            bookmarks.retain(|bookmark| bookmark.get("id").and_then(Value::as_str) != Some(id));
            document["schemaVersion"] = json!(CURRENT_SCHEMA_VERSION);
            Ok(document)
        })
        .await
        .map_err(|error| error.to_string())?;
    Ok(bookmarks_ref())
}

/// Remove bookmarks whose chapter locations disappear with a removed book.
/// Reading-history sessions are intentionally stored separately and retained.
pub async fn remove_bookmarks_for_book(
    store: &ResourceStore,
    book_id: &str,
) -> Result<ResourceRef, String> {
    validate_id(book_id, "bookId")?;
    store
        .update_json_ref(&bookmarks_ref(), move |mut value| {
            let mut document = bookmark_document(&mut value)?;
            document
                .get_mut("bookmarks")
                .and_then(Value::as_array_mut)
                .expect("default bookmark document has an array")
                .retain(|bookmark| bookmark.get("bookId").and_then(Value::as_str) != Some(book_id));
            document["schemaVersion"] = json!(CURRENT_SCHEMA_VERSION);
            Ok(document)
        })
        .await
        .map_err(|error| error.to_string())?;
    Ok(bookmarks_ref())
}

pub async fn reading_history_resource(store: &ResourceStore) -> Result<ResourceRef, String> {
    ensure_document(store, history_ref(), ReadingHistoryDocument::default()).await
}

/// Persist one completed reading visit and recompute its per-book aggregates.
/// Replaying a save with the same `sessionId` replaces that session record
/// instead of adding its duration again.
pub async fn record_reading_session(
    store: &ResourceStore,
    session: ReadingSession,
) -> Result<ResourceRef, String> {
    validate_id(&session.book_id, "bookId")?;
    validate_id(&session.session_id, "sessionId")?;
    if session.ended_at_ms == 0 {
        return Err("Reading session endedAtMs must be positive".to_owned());
    }
    if session.duration_ms == 0 || session.duration_ms > session.ended_at_ms {
        return Err(
            "Reading session duration must be positive and no longer than its timestamp".to_owned(),
        );
    }
    if !(-840..=840).contains(&session.utc_offset_minutes) {
        return Err("Reading session UTC offset must be within -14:00 to +14:00".to_owned());
    }
    let document = store
        .update_json_ref(&history_ref(), move |mut value| {
            let mut document = history_document(&mut value)?;
            if let Some(existing) = document
                .sessions
                .iter_mut()
                .find(|existing| existing.session_id == session.session_id)
            {
                if existing.book_id != session.book_id {
                    return Err("Reading session ID already belongs to another book".to_owned());
                }
                *existing = session;
            } else {
                document.sessions.push(session);
            }
            document.schema_version = CURRENT_SCHEMA_VERSION;
            rebuild_reading_summaries(&mut document);
            serde_json::to_value(document).map_err(|error| error.to_string())
        })
        .await
        .map_err(|error| error.to_string())?;
    let _ = document;
    Ok(history_ref())
}

pub async fn delete_reading_history_for_book(
    store: &ResourceStore,
    book_id: &str,
) -> Result<ResourceRef, String> {
    validate_id(book_id, "bookId")?;
    store
        .update_json_ref(&history_ref(), move |value| {
            let mut document = history_document(&value)?;
            document
                .sessions
                .retain(|session| session.book_id != book_id);
            rebuild_reading_summaries(&mut document);
            serde_json::to_value(document).map_err(|error| error.to_string())
        })
        .await
        .map_err(|error| error.to_string())?;
    Ok(history_ref())
}

pub async fn clear_reading_history(store: &ResourceStore) -> Result<ResourceRef, String> {
    store
        .update_json_ref(&history_ref(), |_| {
            serde_json::to_value(ReadingHistoryDocument::default())
                .map_err(|error| error.to_string())
        })
        .await
        .map_err(|error| error.to_string())?;
    Ok(history_ref())
}

pub async fn replacement_rules_resource(store: &ResourceStore) -> Result<ResourceRef, String> {
    ensure_document(
        store,
        replacements_ref(),
        ReplacementRuleDocument::default(),
    )
    .await
}

/// Save rule configuration only. The frontend applies enabled rules to its
/// rendered, engine-processed chapter; this module does not transform content.
pub async fn upsert_replacement_rule(
    store: &ResourceStore,
    input: DisplayReplacementRuleInput,
) -> Result<ResourceRef, String> {
    let name = input.name.trim().to_owned();
    if name.is_empty() || name.len() > 512 {
        return Err("Replacement rule name must contain 1 to 512 bytes".to_owned());
    }
    if input.pattern.is_empty() || input.pattern.len() > 16_384 {
        return Err("Replacement pattern must contain 1 to 16384 bytes".to_owned());
    }
    if input.replacement.len() > 16_384 {
        return Err("Replacement value exceeds 16 KiB".to_owned());
    }
    let scope = input.scope.trim().to_owned();
    if scope != "all" {
        let book_id = scope
            .strip_prefix("book:")
            .ok_or_else(|| "Replacement scope must be 'all' or 'book:<bookId>'".to_owned())?;
        validate_id(book_id, "bookId")?;
    }
    let id = match input.id {
        Some(id) => {
            validate_id(&id, "replacementRuleId")?;
            id
        }
        None => format!("replacement-{}", uuid::Uuid::new_v4().simple()),
    };
    store
        .update_json_ref(&replacements_ref(), move |mut value| {
            let mut document = replacement_document(&mut value)?;
            let rules = document
                .get_mut("rules")
                .and_then(Value::as_array_mut)
                .expect("default replacement document has an array");
            let rule = json!({
                "id": id,
                "name": name,
                "pattern": input.pattern,
                "replacement": input.replacement,
                "enabled": input.enabled,
                "isRegex": input.is_regex,
                "scope": scope,
            });
            if let Some(position) = rules.iter().position(|candidate| {
                candidate.get("id").and_then(Value::as_str) == Some(id.as_str())
            }) {
                rules[position] = rule;
            } else {
                rules.push(rule);
            }
            document["schemaVersion"] = json!(CURRENT_SCHEMA_VERSION);
            Ok(document)
        })
        .await
        .map_err(|error| error.to_string())?;
    Ok(replacements_ref())
}

pub async fn delete_replacement_rule(
    store: &ResourceStore,
    id: &str,
) -> Result<ResourceRef, String> {
    validate_id(id, "replacementRuleId")?;
    store
        .update_json_ref(&replacements_ref(), |mut value| {
            let mut document = replacement_document(&mut value)?;
            document
                .get_mut("rules")
                .and_then(Value::as_array_mut)
                .expect("default replacement document has an array")
                .retain(|rule| rule.get("id").and_then(Value::as_str) != Some(id));
            document["schemaVersion"] = json!(CURRENT_SCHEMA_VERSION);
            Ok(document)
        })
        .await
        .map_err(|error| error.to_string())?;
    Ok(replacements_ref())
}

/// Assign one book's shelf groups in the shared bookshelf resource.
pub async fn set_book_groups(
    store: &ResourceStore,
    book_id: &str,
    groups: Vec<String>,
) -> Result<ResourceRef, String> {
    validate_id(book_id, "bookId")?;
    let groups = normalize_groups(groups)?;
    store
        .update_json_ref(&store.shelf_ref(), move |mut shelf| {
            ensure_object(&mut shelf, "shelf")?;
            normalize_shelf_groups(&mut shelf)?;
            let books = shelf
                .get_mut("books")
                .and_then(Value::as_array_mut)
                .ok_or_else(|| "Shelf JSON has no books array".to_owned())?;
            let book = books
                .iter_mut()
                .find(|book| book.get("id").and_then(Value::as_str) == Some(book_id))
                .ok_or_else(|| format!("Book '{book_id}' is not on the shelf"))?;
            book["groups"] = json!(groups);
            normalize_shelf_groups(&mut shelf)?;
            Ok(shelf)
        })
        .await
        .map_err(|error| error.to_string())?;
    Ok(store.shelf_ref())
}

/// Create or retain a shelf group even while it has no books.
pub async fn create_shelf_group(
    store: &ResourceStore,
    group_name: &str,
) -> Result<ResourceRef, String> {
    let group_name = normalize_group_name(group_name)?;
    store
        .update_json_ref(&store.shelf_ref(), move |mut shelf| {
            ensure_object(&mut shelf, "shelf")?;
            normalize_shelf_groups(&mut shelf)?;
            let groups = shelf
                .get_mut("groups")
                .and_then(Value::as_array_mut)
                .expect("group registry normalized");
            if !groups
                .iter()
                .any(|existing| existing.as_str() == Some(group_name.as_str()))
            {
                groups.push(json!(group_name));
            }
            Ok(shelf)
        })
        .await
        .map_err(|error| error.to_string())?;
    Ok(store.shelf_ref())
}

/// Rename one shelf group across every book in the shared shelf resource.
pub async fn rename_shelf_group(
    store: &ResourceStore,
    old_name: &str,
    new_name: &str,
) -> Result<ResourceRef, String> {
    let old_name = normalize_group_name(old_name)?;
    let new_name = normalize_group_name(new_name)?;
    store
        .update_json_ref(&store.shelf_ref(), move |mut shelf| {
            ensure_object(&mut shelf, "shelf")?;
            normalize_shelf_groups(&mut shelf)?;
            let books = shelf
                .get_mut("books")
                .and_then(Value::as_array_mut)
                .ok_or_else(|| "Shelf JSON has no books array".to_owned())?;
            for book in books {
                let groups = book["groups"]
                    .as_array_mut()
                    .expect("group field normalized");
                for group in groups.iter_mut() {
                    if group.as_str() == Some(old_name.as_str()) {
                        *group = json!(new_name);
                    }
                }
                let mut seen = Vec::<String>::new();
                groups.retain(|group| {
                    let Some(name) = group.as_str() else {
                        return false;
                    };
                    if seen.iter().any(|existing| existing == name) {
                        false
                    } else {
                        seen.push(name.to_owned());
                        true
                    }
                });
            }
            let groups = shelf
                .get_mut("groups")
                .and_then(Value::as_array_mut)
                .expect("group registry normalized");
            let old_index = groups
                .iter()
                .position(|group| group.as_str() == Some(old_name.as_str()))
                .ok_or_else(|| format!("Shelf group '{old_name}' does not exist"))?;
            groups[old_index] = json!(new_name);
            normalize_shelf_groups(&mut shelf)?;
            Ok(shelf)
        })
        .await
        .map_err(|error| error.to_string())?;
    Ok(store.shelf_ref())
}

/// Remove one shelf group from all books while preserving the books themselves.
pub async fn delete_shelf_group(
    store: &ResourceStore,
    group_name: &str,
) -> Result<ResourceRef, String> {
    let group_name = normalize_group_name(group_name)?;
    store
        .update_json_ref(&store.shelf_ref(), move |mut shelf| {
            ensure_object(&mut shelf, "shelf")?;
            normalize_shelf_groups(&mut shelf)?;
            let books = shelf
                .get_mut("books")
                .and_then(Value::as_array_mut)
                .ok_or_else(|| "Shelf JSON has no books array".to_owned())?;
            for book in books {
                let groups = book["groups"]
                    .as_array_mut()
                    .expect("group field normalized");
                groups.retain(|group| group.as_str() != Some(group_name.as_str()));
            }
            shelf
                .get_mut("groups")
                .and_then(Value::as_array_mut)
                .expect("group registry normalized")
                .retain(|group| group.as_str() != Some(group_name.as_str()));
            normalize_shelf_groups(&mut shelf)?;
            Ok(shelf)
        })
        .await
        .map_err(|error| error.to_string())?;
    Ok(store.shelf_ref())
}

/// Store the shelf's order and sort books in the shared shelf JSON document.
pub async fn set_shelf_sort(
    store: &ResourceStore,
    key: ShelfSortKey,
    order: ShelfSortOrder,
) -> Result<ResourceRef, String> {
    store
        .update_json_ref(&store.shelf_ref(), move |mut shelf| {
            ensure_object(&mut shelf, "shelf")?;
            shelf["sort"] = serde_json::to_value(key).map_err(|error| error.to_string())?;
            shelf["sortOrder"] = serde_json::to_value(order).map_err(|error| error.to_string())?;
            apply_shelf_sort(&mut shelf)?;
            Ok(shelf)
        })
        .await
        .map_err(|error| error.to_string())?;
    Ok(store.shelf_ref())
}

/// Apply the sort settings already stored on a shelf document. The application
/// service uses this after progress changes the metadata from which the order
/// is derived, while preserving explicit custom order.
pub(crate) fn apply_shelf_sort(shelf: &mut Value) -> Result<(), String> {
    ensure_object(shelf, "shelf")?;
    let key = shelf
        .get("sort")
        .cloned()
        .map(serde_json::from_value)
        .transpose()
        .map_err(|error| format!("Invalid shelf sort key: {error}"))?
        .unwrap_or(ShelfSortKey::UpdatedAt);
    let order = shelf
        .get("sortOrder")
        .cloned()
        .map(serde_json::from_value)
        .transpose()
        .map_err(|error| format!("Invalid shelf sort order: {error}"))?
        .unwrap_or(ShelfSortOrder::Descending);
    let books = shelf
        .get_mut("books")
        .and_then(Value::as_array_mut)
        .ok_or_else(|| "Shelf JSON has no books array".to_owned())?;
    if key != ShelfSortKey::Custom {
        books.sort_by(|left, right| {
            let ordering = compare_books(left, right, key);
            match order {
                ShelfSortOrder::Ascending => ordering,
                ShelfSortOrder::Descending => ordering.reverse(),
            }
        });
    }
    Ok(())
}

/// Persist an explicit user order. The provided IDs must be a permutation of
/// the current shelf so books cannot accidentally disappear from the index.
pub async fn set_shelf_order(
    store: &ResourceStore,
    ordered_book_ids: Vec<String>,
) -> Result<ResourceRef, String> {
    store
        .update_json_ref(&store.shelf_ref(), move |mut shelf| {
            ensure_object(&mut shelf, "shelf")?;
            normalize_shelf_groups(&mut shelf)?;
            let books = shelf
                .get_mut("books")
                .and_then(Value::as_array_mut)
                .ok_or_else(|| "Shelf JSON has no books array".to_owned())?;
            if books.len() != ordered_book_ids.len() {
                return Err("Custom shelf order must include every book exactly once".to_owned());
            }
            let mut by_id = BTreeMap::new();
            for book in std::mem::take(books) {
                let id = book
                    .get("id")
                    .and_then(Value::as_str)
                    .ok_or_else(|| "Shelf book is missing its ID".to_owned())?;
                if by_id.insert(id.to_owned(), book).is_some() {
                    return Err("Shelf contains duplicate book IDs".to_owned());
                }
            }
            let mut reordered = Vec::with_capacity(ordered_book_ids.len());
            for id in ordered_book_ids {
                let book = by_id.remove(&id).ok_or_else(|| {
                    "Custom shelf order contains an unknown or duplicate book ID".to_owned()
                })?;
                reordered.push(book);
            }
            if !by_id.is_empty() {
                return Err("Custom shelf order omitted one or more books".to_owned());
            }
            *books = reordered;
            shelf["sort"] = json!("custom");
            shelf["sortOrder"] = json!("ascending");
            Ok(shelf)
        })
        .await
        .map_err(|error| error.to_string())?;
    Ok(store.shelf_ref())
}

async fn ensure_document<T: Serialize>(
    store: &ResourceStore,
    reference: ResourceRef,
    default: T,
) -> Result<ResourceRef, String> {
    let default = serde_json::to_value(default).map_err(|error| error.to_string())?;
    store
        .update_json_ref(&reference, move |value| match value {
            Value::Null => Ok(default),
            value => Ok(value),
        })
        .await
        .map_err(|error| error.to_string())?;
    Ok(reference)
}

fn bookmark_document(value: &mut Value) -> Result<Value, String> {
    ensure_object(value, "bookmark")?;
    value
        .as_object_mut()
        .expect("object checked")
        .entry("schemaVersion")
        .or_insert_with(|| json!(CURRENT_SCHEMA_VERSION));
    value
        .as_object_mut()
        .expect("object checked")
        .entry("bookmarks")
        .or_insert_with(|| json!([]));
    if !value["bookmarks"].is_array() {
        return Err("Bookmark JSON field 'bookmarks' must be an array".to_owned());
    }
    Ok(value.clone())
}

fn history_document(value: &Value) -> Result<ReadingHistoryDocument, String> {
    if value.is_null() {
        return Ok(ReadingHistoryDocument::default());
    }
    serde_json::from_value(value.clone())
        .map_err(|error| format!("Invalid reading history JSON: {error}"))
}

fn replacement_document(value: &mut Value) -> Result<Value, String> {
    ensure_object(value, "replacement rules")?;
    value
        .as_object_mut()
        .expect("object checked")
        .entry("schemaVersion")
        .or_insert_with(|| json!(CURRENT_SCHEMA_VERSION));
    value
        .as_object_mut()
        .expect("object checked")
        .entry("rules")
        .or_insert_with(|| json!([]));
    if !value["rules"].is_array() {
        return Err("Replacement JSON field 'rules' must be an array".to_owned());
    }
    Ok(value.clone())
}

fn ensure_object(value: &mut Value, document_name: &str) -> Result<(), String> {
    if value.is_null() {
        *value = json!({});
    }
    if !value.is_object() {
        return Err(format!("{document_name} JSON must be an object"));
    }
    Ok(())
}

fn rebuild_reading_summaries(document: &mut ReadingHistoryDocument) {
    let mut summaries = BTreeMap::<String, BookReadingSummary>::new();
    let mut daily = BTreeMap::<String, MutableDailySummary>::new();
    let mut total_duration_ms = 0u64;
    for session in &document.sessions {
        total_duration_ms = total_duration_ms.saturating_add(session.duration_ms);
        let summary =
            summaries
                .entry(session.book_id.clone())
                .or_insert_with(|| BookReadingSummary {
                    book_id: session.book_id.clone(),
                    session_count: 0,
                    total_duration_ms: 0,
                    last_read_at_ms: 0,
                });
        summary.session_count = summary.session_count.saturating_add(1);
        summary.total_duration_ms = summary
            .total_duration_ms
            .saturating_add(session.duration_ms);
        summary.last_read_at_ms = summary.last_read_at_ms.max(session.ended_at_ms);

        for (day, duration) in split_session_by_local_day(session) {
            let entry = daily.entry(day).or_default();
            entry.session_count = entry.session_count.saturating_add(1);
            entry.total_duration_ms = entry.total_duration_ms.saturating_add(duration);
            let book = entry
                .books
                .entry(session.book_id.clone())
                .or_insert_with(|| MutableBookDailySummary {
                    book_id: session.book_id.clone(),
                    session_count: 0,
                    total_duration_ms: 0,
                });
            book.session_count = book.session_count.saturating_add(1);
            book.total_duration_ms = book.total_duration_ms.saturating_add(duration);
        }
    }
    document.books = summaries.into_values().collect();
    document
        .books
        .sort_by(|left, right| right.last_read_at_ms.cmp(&left.last_read_at_ms));
    document.total_duration_ms = total_duration_ms;
    document.total_sessions = document.sessions.len() as u64;
    document.days = daily
        .into_iter()
        .rev()
        .map(|(day, value)| DailyReadingSummary {
            day,
            session_count: value.session_count,
            total_duration_ms: value.total_duration_ms,
            books: value
                .books
                .into_values()
                .map(|book| BookDailySummary {
                    book_id: book.book_id,
                    session_count: book.session_count,
                    total_duration_ms: book.total_duration_ms,
                })
                .collect(),
        })
        .collect();
}

#[derive(Default)]
struct MutableDailySummary {
    session_count: u64,
    total_duration_ms: u64,
    books: BTreeMap<String, MutableBookDailySummary>,
}

struct MutableBookDailySummary {
    book_id: String,
    session_count: u64,
    total_duration_ms: u64,
}

fn split_session_by_local_day(session: &ReadingSession) -> Vec<(String, u64)> {
    const DAY_MS: i128 = 86_400_000;
    const MINUTE_MS: i128 = 60_000;
    let end = session.ended_at_ms as i128;
    let mut cursor = end - session.duration_ms as i128;
    let offset = session.utc_offset_minutes as i128 * MINUTE_MS;
    let mut pieces = Vec::new();
    while cursor < end {
        let day_number = (cursor + offset).div_euclid(DAY_MS);
        let next_utc_day = (day_number + 1) * DAY_MS - offset;
        let segment_end = end.min(next_utc_day);
        if segment_end <= cursor {
            break;
        }
        pieces.push((civil_day_key(day_number), (segment_end - cursor) as u64));
        cursor = segment_end;
    }
    pieces
}

/// Convert days since 1970-01-01 to a proleptic Gregorian `YYYYMMDD` key.
fn civil_day_key(days_since_epoch: i128) -> String {
    let z = days_since_epoch as i64 + 719_468;
    let era = (if z >= 0 { z } else { z - 146_096 }).div_euclid(146_097);
    let day_of_era = z - era * 146_097;
    let year_of_era =
        (day_of_era - day_of_era / 1_460 + day_of_era / 36_524 - day_of_era / 146_096) / 365;
    let mut year = year_of_era + era * 400;
    let day_of_year = day_of_era - (365 * year_of_era + year_of_era / 4 - year_of_era / 100);
    let month_prime = (5 * day_of_year + 2) / 153;
    let day = day_of_year - (153 * month_prime + 2) / 5 + 1;
    let month = month_prime + if month_prime < 10 { 3 } else { -9 };
    year += (month <= 2) as i64;
    format!("{year:04}{month:02}{day:02}")
}

fn normalize_groups(groups: Vec<String>) -> Result<Vec<String>, String> {
    let mut result = Vec::new();
    for group in groups {
        let group = group.trim();
        let group = normalize_group_name(group)?;
        if !result.iter().any(|existing: &String| existing == &group) {
            result.push(group);
        }
    }
    if result.len() > 64 {
        return Err("A book cannot belong to more than 64 shelf groups".to_owned());
    }
    Ok(result)
}

fn normalize_shelf_groups(shelf: &mut Value) -> Result<(), String> {
    let group_values = match shelf.get_mut("groups") {
        None => {
            shelf["groups"] = json!([]);
            shelf
                .get_mut("groups")
                .and_then(Value::as_array_mut)
                .expect("new group registry is an array")
        }
        Some(Value::Array(groups)) => groups,
        Some(_) => return Err("Shelf groups must be a JSON array".to_owned()),
    };
    let mut registry = Vec::<String>::new();
    for group in group_values.iter() {
        let name = group
            .as_str()
            .ok_or_else(|| "Shelf group names must be strings".to_owned())?;
        let name = normalize_group_name(name)?;
        if !registry.iter().any(|existing| existing == &name) {
            registry.push(name);
        }
    }
    let books = shelf
        .get_mut("books")
        .and_then(Value::as_array_mut)
        .ok_or_else(|| "Shelf JSON has no books array".to_owned())?;
    for book in books {
        let book = book
            .as_object_mut()
            .ok_or_else(|| "Shelf book must be a JSON object".to_owned())?;
        let book_groups = match book.get_mut("groups") {
            None => {
                book.insert("groups".to_owned(), json!([]));
                book.get_mut("groups")
                    .and_then(Value::as_array_mut)
                    .expect("new book group value is an array")
            }
            Some(Value::Array(groups)) => groups,
            Some(_) => return Err("Shelf book groups must be a JSON array".to_owned()),
        };
        let mut normalized_book_groups = Vec::<String>::new();
        for group in book_groups.iter() {
            let name = group
                .as_str()
                .ok_or_else(|| "Book group names must be strings".to_owned())?;
            let name = normalize_group_name(name)?;
            if !normalized_book_groups
                .iter()
                .any(|existing| existing == &name)
            {
                normalized_book_groups.push(name.clone());
            }
            if !registry.iter().any(|existing| existing == &name) {
                registry.push(name);
            }
        }
        *book_groups = normalized_book_groups
            .into_iter()
            .map(Value::String)
            .collect();
    }
    shelf["groups"] = json!(registry);
    Ok(())
}

fn normalize_group_name(group: &str) -> Result<String, String> {
    let group = group.trim();
    if group.is_empty() || group.len() > 128 {
        return Err("Shelf group names must contain 1 to 128 bytes".to_owned());
    }
    Ok(group.to_owned())
}

fn compare_books(left: &Value, right: &Value, key: ShelfSortKey) -> std::cmp::Ordering {
    match key {
        ShelfSortKey::UpdatedAt => progress_updated_at(left).cmp(&progress_updated_at(right)),
        ShelfSortKey::Title => text_field(left, "title").cmp(&text_field(right, "title")),
        ShelfSortKey::Author => text_field(left, "author").cmp(&text_field(right, "author")),
        ShelfSortKey::LatestChapter => {
            text_field(left, "latestChapter").cmp(&text_field(right, "latestChapter"))
        }
        ShelfSortKey::Progress => progress_chapter_index(left).cmp(&progress_chapter_index(right)),
        ShelfSortKey::Custom => std::cmp::Ordering::Equal,
    }
}

fn text_field(value: &Value, key: &str) -> String {
    value
        .get(key)
        .and_then(Value::as_str)
        .unwrap_or_default()
        .to_lowercase()
}

fn progress_updated_at(value: &Value) -> u64 {
    value["progress"]["updatedAtMs"]
        .as_u64()
        .unwrap_or_default()
}

fn progress_chapter_index(value: &Value) -> u64 {
    value["progress"]["chapterIndex"]
        .as_u64()
        .unwrap_or_default()
}

fn validate_id(id: &str, field: &str) -> Result<(), String> {
    if id.is_empty()
        || id.len() > 128
        || !id
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || byte == b'-' || byte == b'_')
    {
        return Err(format!("Invalid {field}"));
    }
    Ok(())
}

fn bookmarks_ref() -> ResourceRef {
    ResourceRef::new(BOOKMARKS_PATH).expect("static bookmark resource reference is valid")
}

fn history_ref() -> ResourceRef {
    ResourceRef::new(HISTORY_PATH).expect("static reading history reference is valid")
}

fn replacements_ref() -> ResourceRef {
    ResourceRef::new(REPLACEMENTS_PATH).expect("static replacement resource reference is valid")
}

fn default_replacement_scope() -> String {
    "all".to_owned()
}

fn current_schema_version() -> u32 {
    CURRENT_SCHEMA_VERSION
}

fn now_ms() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|duration| duration.as_millis() as u64)
        .unwrap_or_default()
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    async fn store() -> (tempfile::TempDir, ResourceStore) {
        let directory = tempdir().unwrap();
        let store = ResourceStore::open(directory.path()).unwrap();
        (directory, store)
    }

    async fn load_bookmarks(store: &ResourceStore) -> BookmarkDocument {
        serde_json::from_value(store.read_json_ref(&bookmarks_ref()).await.unwrap()).unwrap()
    }

    async fn load_history(store: &ResourceStore) -> ReadingHistoryDocument {
        serde_json::from_value(store.read_json_ref(&history_ref()).await.unwrap()).unwrap()
    }

    #[tokio::test]
    async fn bookmark_crud_keeps_creation_time_and_utf8_note() {
        let (_directory, store) = store().await;
        let reference = upsert_bookmark(
            &store,
            BookmarkInput {
                id: Some("bookmark-one".to_owned()),
                book_id: "book-one".to_owned(),
                chapter_index: 7,
                offset: 128,
                note: "这一段写得很好".to_owned(),
            },
        )
        .await
        .unwrap();
        let created = load_bookmarks(&store).await.bookmarks.remove(0);
        assert_eq!(reference, bookmarks_ref());
        assert_eq!(created.note, "这一段写得很好");
        assert_eq!(created.chapter_index, 7);
        assert_eq!(created.offset, 128);

        upsert_bookmark(
            &store,
            BookmarkInput {
                id: Some("bookmark-one".to_owned()),
                book_id: "book-one".to_owned(),
                chapter_index: 8,
                offset: 256,
                note: "更新备注 🌱".to_owned(),
            },
        )
        .await
        .unwrap();
        let updated = load_bookmarks(&store).await.bookmarks.remove(0);
        assert_eq!(updated.created_at_ms, created.created_at_ms);
        assert!(updated.updated_at_ms >= created.updated_at_ms);
        assert_eq!(updated.note, "更新备注 🌱");

        delete_bookmark(&store, "bookmark-one").await.unwrap();
        assert!(load_bookmarks(&store).await.bookmarks.is_empty());
    }

    #[tokio::test]
    async fn bookmark_updates_survive_restart_and_concurrent_writes() {
        let (directory, store) = store().await;
        let mut tasks = Vec::new();
        for index in 0..12 {
            let store = store.clone();
            tasks.push(tokio::spawn(async move {
                upsert_bookmark(
                    &store,
                    BookmarkInput {
                        id: Some(format!("bookmark-{index}")),
                        book_id: "book-one".to_owned(),
                        chapter_index: index,
                        offset: index as u64,
                        note: format!("并发标记 {index}"),
                    },
                )
                .await
                .unwrap();
            }));
        }
        for task in tasks {
            task.await.unwrap();
        }
        assert_eq!(load_bookmarks(&store).await.bookmarks.len(), 12);
        drop(store);

        let reopened = ResourceStore::open(directory.path()).unwrap();
        let document = load_bookmarks(&reopened).await;
        assert_eq!(document.bookmarks.len(), 12);
        assert!(document
            .bookmarks
            .iter()
            .any(|bookmark| bookmark.note == "并发标记 11"));
    }

    #[tokio::test]
    async fn removing_a_book_cascades_bookmarks_but_retains_reading_history() {
        let (_directory, store) = store().await;
        for (id, book_id) in [("bookmark-one", "book-one"), ("bookmark-two", "book-two")] {
            upsert_bookmark(
                &store,
                BookmarkInput {
                    id: Some(id.to_owned()),
                    book_id: book_id.to_owned(),
                    chapter_index: 0,
                    offset: 0,
                    note: String::new(),
                },
            )
            .await
            .unwrap();
        }
        record_reading_session(
            &store,
            ReadingSession {
                book_id: "book-one".to_owned(),
                session_id: "session-one".to_owned(),
                duration_ms: 2_000,
                ended_at_ms: 10_000,
                utc_offset_minutes: 0,
            },
        )
        .await
        .unwrap();

        remove_bookmarks_for_book(&store, "book-one").await.unwrap();

        let bookmarks = load_bookmarks(&store).await;
        assert_eq!(bookmarks.bookmarks.len(), 1);
        assert_eq!(bookmarks.bookmarks[0].book_id, "book-two");
        let history = load_history(&store).await;
        assert_eq!(history.sessions.len(), 1);
        assert_eq!(history.sessions[0].book_id, "book-one");
    }

    #[tokio::test]
    async fn reading_sessions_are_idempotent_and_aggregate_by_book() {
        let (_directory, store) = store().await;
        let visit = ReadingSession {
            book_id: "book-one".to_owned(),
            session_id: "visit-one".to_owned(),
            duration_ms: 90_000,
            ended_at_ms: 100_000,
            utc_offset_minutes: 0,
        };
        record_reading_session(&store, visit.clone()).await.unwrap();
        record_reading_session(&store, visit).await.unwrap();
        record_reading_session(
            &store,
            ReadingSession {
                book_id: "book-one".to_owned(),
                session_id: "visit-two".to_owned(),
                duration_ms: 30_000,
                ended_at_ms: 200_000,
                utc_offset_minutes: 0,
            },
        )
        .await
        .unwrap();
        record_reading_session(
            &store,
            ReadingSession {
                book_id: "book-two".to_owned(),
                session_id: "visit-three".to_owned(),
                duration_ms: 60_000,
                ended_at_ms: 300_000,
                utc_offset_minutes: 0,
            },
        )
        .await
        .unwrap();

        let history = load_history(&store).await;
        assert_eq!(history.total_sessions, 3);
        assert_eq!(history.total_duration_ms, 180_000);
        let first = history
            .books
            .iter()
            .find(|book| book.book_id == "book-one")
            .unwrap();
        assert_eq!(first.session_count, 2);
        assert_eq!(first.total_duration_ms, 120_000);
        assert_eq!(first.last_read_at_ms, 200_000);
        assert_eq!(
            history
                .days
                .iter()
                .map(|day| day.total_duration_ms)
                .sum::<u64>(),
            180_000
        );
    }

    #[tokio::test]
    async fn reading_time_is_split_across_local_calendar_days() {
        let (_directory, store) = store().await;
        let reference = record_reading_session(
            &store,
            ReadingSession {
                book_id: "book-one".to_owned(),
                session_id: "midnight-visit".to_owned(),
                duration_ms: 60_000,
                // 1970-01-01 16:00 UTC is midnight on Jan 2 at UTC+08.
                ended_at_ms: 16 * 60 * 60 * 1_000 + 30_000,
                utc_offset_minutes: 480,
            },
        )
        .await
        .unwrap();
        let history: ReadingHistoryDocument =
            serde_json::from_value(store.read_json_ref(&reference).await.unwrap()).unwrap();
        assert_eq!(history.days.len(), 2);
        assert_eq!(history.days[0].day, "19700102");
        assert_eq!(history.days[0].total_duration_ms, 30_000);
        assert_eq!(history.days[1].day, "19700101");
        assert_eq!(history.days[1].total_duration_ms, 30_000);
        assert_eq!(history.total_duration_ms, 60_000);
    }

    #[tokio::test]
    async fn reading_history_delete_and_clear_rebuild_aggregates() {
        let (_directory, store) = store().await;
        for (book_id, session_id) in [("book-one", "visit-one"), ("book-two", "visit-two")] {
            record_reading_session(
                &store,
                ReadingSession {
                    book_id: book_id.to_owned(),
                    session_id: session_id.to_owned(),
                    duration_ms: 1_000,
                    ended_at_ms: 10_000,
                    utc_offset_minutes: 0,
                },
            )
            .await
            .unwrap();
        }
        delete_reading_history_for_book(&store, "book-one")
            .await
            .unwrap();
        let history = load_history(&store).await;
        assert_eq!(history.total_sessions, 1);
        assert_eq!(history.books.len(), 1);
        assert_eq!(history.books[0].book_id, "book-two");

        clear_reading_history(&store).await.unwrap();
        let history = load_history(&store).await;
        assert!(history.sessions.is_empty());
        assert!(history.books.is_empty());
        assert!(history.days.is_empty());
        assert_eq!(history.total_duration_ms, 0);
    }

    #[tokio::test]
    async fn replacement_rules_are_stored_without_transforming_content() {
        let (_directory, store) = store().await;
        let reference = upsert_replacement_rule(
            &store,
            DisplayReplacementRuleInput {
                id: Some("replace-one".to_owned()),
                name: "清理广告".to_owned(),
                pattern: "广告.*?结束".to_owned(),
                replacement: "".to_owned(),
                enabled: true,
                is_regex: true,
                scope: "book:book-one".to_owned(),
            },
        )
        .await
        .unwrap();
        assert_eq!(reference, replacements_ref());
        let document: ReplacementRuleDocument =
            serde_json::from_value(store.read_json_ref(&reference).await.unwrap()).unwrap();
        let rule = &document.rules[0];
        assert_eq!(rule.name, "清理广告");
        assert_eq!(rule.pattern, "广告.*?结束");
        assert_eq!(rule.scope, "book:book-one");
        delete_replacement_rule(&store, "replace-one")
            .await
            .unwrap();
        let document: ReplacementRuleDocument =
            serde_json::from_value(store.read_json_ref(&reference).await.unwrap()).unwrap();
        assert!(document.rules.is_empty());
    }

    #[tokio::test]
    async fn shelf_groups_and_sort_modify_the_shared_shelf_json() {
        let (_directory, store) = store().await;
        let shelf_ref = store.shelf_ref();
        store
            .write_json_ref(
                &shelf_ref,
                &json!({
                    "schemaVersion": CURRENT_SCHEMA_VERSION,
                    "sort": "updatedAt",
                    "sortOrder": "descending",
                    "books": [
                        { "id": "book-a", "title": "Beta", "author": "Gamma", "progress": { "updatedAtMs": 10, "chapterIndex": 2 } },
                        { "id": "book-b", "title": "Alpha", "author": "Delta", "progress": { "updatedAtMs": 20, "chapterIndex": 1 } }
                    ]
                }),
            )
            .await
            .unwrap();
        create_shelf_group(&store, "空分组").await.unwrap();
        set_book_groups(
            &store,
            "book-a",
            vec!["稍后阅读".into(), "  喜欢  ".into(), "稍后阅读".into()],
        )
        .await
        .unwrap();
        set_shelf_sort(&store, ShelfSortKey::Title, ShelfSortOrder::Ascending)
            .await
            .unwrap();
        let shelf = store.read_json_ref(&shelf_ref).await.unwrap();
        assert_eq!(shelf["books"][0]["id"], "book-b");
        assert_eq!(shelf["books"][1]["groups"], json!(["稍后阅读", "喜欢"]));
        assert_eq!(shelf["groups"], json!(["空分组", "稍后阅读", "喜欢"]));
        assert_eq!(shelf["sort"], "title");
        assert_eq!(shelf["sortOrder"], "ascending");

        rename_shelf_group(&store, "稍后阅读", "待读")
            .await
            .unwrap();
        delete_shelf_group(&store, "喜欢").await.unwrap();
        set_shelf_order(&store, vec!["book-a".into(), "book-b".into()])
            .await
            .unwrap();
        let shelf = store.read_json_ref(&shelf_ref).await.unwrap();
        assert_eq!(shelf["books"][0]["id"], "book-a");
        assert_eq!(shelf["books"][0]["groups"], json!(["待读"]));
        assert_eq!(shelf["books"][1]["groups"], json!([]));
        assert_eq!(shelf["groups"], json!(["空分组", "待读"]));
        assert_eq!(shelf["sort"], "custom");

        let restarted = ResourceStore::open(_directory.path()).unwrap();
        let restarted_shelf = restarted.read_json_ref(&shelf_ref).await.unwrap();
        assert_eq!(restarted_shelf["groups"], json!(["空分组", "待读"]));
    }
}
